# coding: utf-8

"""
    RAG API

    API for RAG

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from endpoints.models.chat_rag_data import ChatRAGData
from endpoints.models.chat_text_data import ChatTextData
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class MessageData(BaseModel):
    """
    MessageData
    """ # noqa: E501
    text_data: Optional[ChatTextData] = None
    rag_data: Optional[ChatRAGData] = None
    __properties: ClassVar[List[str]] = ["text_data", "rag_data"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MessageData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of text_data
        if self.text_data:
            _dict['text_data'] = self.text_data.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rag_data
        if self.rag_data:
            _dict['rag_data'] = self.rag_data.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of MessageData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "text_data": ChatTextData.from_dict(obj.get("text_data")) if obj.get("text_data") is not None else None,
            "rag_data": ChatRAGData.from_dict(obj.get("rag_data")) if obj.get("rag_data") is not None else None
        })
        return _obj


