# coding: utf-8

"""
    RAG API

    API for RAG

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from endpoints.apis.chat_api import router as ChatApiRouter
from endpoints.apis.document_api import router as DocumentApiRouter

app = FastAPI(
    title="RAG API",
    description="API for RAG",
    version="1.0.0",
)

app.include_router(ChatApiRouter)
app.include_router(DocumentApiRouter)
